-- Description : 20-web-ddl.sql - 📱 Web 알림마당 PostgreSQL Table DDL
-- Author : Shiwoo Min
-- Date : 2025-02-09
-- Schema : Web 알림마당 (공지사항, 게시판, 갤러리, 식단표, 프로그램)
-- Note : Extensions는 00-extensions.sql에서 이미 생성됨

-- ============================================
-- Utility Functions
-- ============================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS 'UPDATE 시 updated_at 컬럼을 자동으로 현재 시각으로 갱신하는 트리거 함수';

-- ============================================
-- 1. 기본 테이블 (의존성)
-- ============================================

-- DEPARTMENTS (부서)
CREATE TABLE departments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE departments IS '부서 정보 - 조직 내 부서 구조를 정의하는 마스터 테이블';
COMMENT ON COLUMN departments.id IS '부서 ID (Primary Key)';
COMMENT ON COLUMN departments.code IS '부서 코드 (고유값)';
COMMENT ON COLUMN departments.name IS '부서명';
COMMENT ON COLUMN departments.description IS '부서 설명';
COMMENT ON COLUMN departments.is_active IS '활성화 여부';
COMMENT ON COLUMN departments.created_at IS '생성일시';
COMMENT ON COLUMN departments.updated_at IS '수정일시';

CREATE TRIGGER trg_departments_u
BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- EMPLOYEE_ROLES (직원 역할)
CREATE TABLE employee_roles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE employee_roles IS '직원 역할/권한 정보 - 직원의 역할과 권한을 정의하는 마스터 테이블';
COMMENT ON COLUMN employee_roles.id IS '역할 ID (Primary Key)';
COMMENT ON COLUMN employee_roles.code IS '역할 코드 (고유값)';
COMMENT ON COLUMN employee_roles.name IS '역할명';
COMMENT ON COLUMN employee_roles.description IS '역할 설명';
COMMENT ON COLUMN employee_roles.permissions IS '권한 설정 (JSON)';
COMMENT ON COLUMN employee_roles.created_at IS '생성일시';
COMMENT ON COLUMN employee_roles.updated_at IS '수정일시';

CREATE TRIGGER trg_employee_roles_u
BEFORE UPDATE ON employee_roles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- EMPLOYEES (직원)
CREATE TABLE employees (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  role_id         BIGINT REFERENCES employee_roles(id) ON DELETE SET NULL,
  email           CITEXT UNIQUE,
  password_hash   TEXT,
  name            TEXT NOT NULL,
  phone_number    TEXT,
  hire_date       DATE,
  resign_date     DATE,
  status          TEXT NOT NULL DEFAULT 'ACTIVE',
  is_admin        BOOLEAN NOT NULL DEFAULT FALSE,
  meta            JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT employees_status_ck
    CHECK (status IN ('ACTIVE','ON_LEAVE','INACTIVE'))
);

COMMENT ON TABLE employees IS '직원 정보 - 시스템 사용자 및 요양원 직원 정보를 관리하는 핵심 테이블';
COMMENT ON COLUMN employees.id IS '직원 ID (Primary Key)';
COMMENT ON COLUMN employees.department_id IS '부서 ID (외래키) - departments 테이블 참조';
COMMENT ON COLUMN employees.role_id IS '역할 ID (외래키) - employee_roles 테이블 참조';
COMMENT ON COLUMN employees.email IS '이메일 (로그인 ID, 고유값, 대소문자 구분 안함)';
COMMENT ON COLUMN employees.password_hash IS '비밀번호 해시 (민감정보)';
COMMENT ON COLUMN employees.name IS '직원명';
COMMENT ON COLUMN employees.phone_number IS '전화번호';
COMMENT ON COLUMN employees.hire_date IS '입사일';
COMMENT ON COLUMN employees.resign_date IS '퇴사일';
COMMENT ON COLUMN employees.status IS '재직 상태 - ACTIVE: 재직중, ON_LEAVE: 휴직중, INACTIVE: 퇴사';
COMMENT ON COLUMN employees.is_admin IS '관리자 여부';
COMMENT ON COLUMN employees.meta IS '추가 메타데이터 (JSON)';
COMMENT ON COLUMN employees.last_login_at IS '마지막 로그인 일시';
COMMENT ON COLUMN employees.created_at IS '생성일시';
COMMENT ON COLUMN employees.updated_at IS '수정일시';

CREATE TRIGGER trg_employees_u
BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- FILE_STORAGE (파일 저장소)
CREATE TABLE file_storage (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket          TEXT NOT NULL DEFAULT 'default',
  path            TEXT NOT NULL,
  original_name   TEXT,
  mime_type       TEXT,
  size_bytes      BIGINT,
  checksum        TEXT,
  created_by      BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE file_storage IS '파일 저장소 - S3, 로컬 등에 저장된 파일의 메타데이터 관리';
COMMENT ON COLUMN file_storage.id IS '파일 ID (Primary Key)';
COMMENT ON COLUMN file_storage.bucket IS '저장소 버킷';
COMMENT ON COLUMN file_storage.path IS '파일 경로 - 버킷 내 상대 경로';
COMMENT ON COLUMN file_storage.original_name IS '원본 파일명';
COMMENT ON COLUMN file_storage.mime_type IS 'MIME 타입';
COMMENT ON COLUMN file_storage.size_bytes IS '파일 크기 (바이트)';
COMMENT ON COLUMN file_storage.checksum IS '체크섬 (MD5, SHA256 등)';
COMMENT ON COLUMN file_storage.created_by IS '업로드자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN file_storage.created_at IS '생성일시';

CREATE UNIQUE INDEX uq_file_storage_bucket_path
  ON file_storage(bucket, path);

-- RESIDENTS (입소자 - 프로그램 참석용)
CREATE TABLE residents (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  birthday          DATE,
  gender            TEXT,
  admission_date    DATE,
  discharge_date    DATE,
  status            TEXT NOT NULL DEFAULT 'ADMITTED',
  guardian_name     TEXT,
  guardian_phone    TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT residents_status_ck
    CHECK (status IN ('ADMITTED','ON_LEAVE','DISCHARGED','PENDING'))
);

COMMENT ON TABLE residents IS '입소자 정보 - 프로그램 참석 기록을 위한 최소 정보';
COMMENT ON COLUMN residents.id IS '입소자 ID (Primary Key)';
COMMENT ON COLUMN residents.code IS '입소자 코드 (고유값)';
COMMENT ON COLUMN residents.name IS '입소자명';
COMMENT ON COLUMN residents.birthday IS '생년월일';
COMMENT ON COLUMN residents.gender IS '성별 - M: 남성, F: 여성, OTHER: 기타';
COMMENT ON COLUMN residents.admission_date IS '입소일';
COMMENT ON COLUMN residents.discharge_date IS '퇴소일';
COMMENT ON COLUMN residents.status IS '입소 상태';
COMMENT ON COLUMN residents.guardian_name IS '보호자명';
COMMENT ON COLUMN residents.guardian_phone IS '보호자 연락처';
COMMENT ON COLUMN residents.created_at IS '생성일시';
COMMENT ON COLUMN residents.updated_at IS '수정일시';

CREATE TRIGGER trg_residents_u
BEFORE UPDATE ON residents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 2. 공지사항 (2 Tables)
-- ============================================

-- NOTICES (공지사항)
CREATE TABLE notices (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  category      TEXT DEFAULT 'GENERAL',
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  view_count    INT NOT NULL DEFAULT 0,
  published_at  TIMESTAMPTZ,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notices IS '공지사항 - 시설 내부 공지 및 알림';
COMMENT ON COLUMN notices.id IS '공지 ID (Primary Key)';
COMMENT ON COLUMN notices.title IS '공지 제목';
COMMENT ON COLUMN notices.content IS '공지 내용 (HTML)';
COMMENT ON COLUMN notices.category IS '카테고리 - GENERAL: 일반, URGENT: 긴급, EVENT: 행사, EDUCATION: 교육, MAINTENANCE: 유지보수';
COMMENT ON COLUMN notices.is_pinned IS '상단 고정 여부';
COMMENT ON COLUMN notices.is_active IS '활성화 여부';
COMMENT ON COLUMN notices.view_count IS '조회수';
COMMENT ON COLUMN notices.published_at IS '게시일시';
COMMENT ON COLUMN notices.created_by IS '작성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN notices.created_at IS '생성일시';
COMMENT ON COLUMN notices.updated_at IS '수정일시';

CREATE INDEX idx_notices_active_published
  ON notices(is_active, published_at DESC)
  WHERE is_active = true;

CREATE INDEX idx_notices_pinned_created
  ON notices(is_pinned DESC, created_at DESC)
  WHERE is_active = true;

CREATE TRIGGER trg_notices_u
BEFORE UPDATE ON notices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- NOTICE_FILES (공지사항 첨부파일)
CREATE TABLE notice_files (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id   BIGINT NOT NULL REFERENCES notices(id) ON DELETE CASCADE,
  file_id     BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notice_files IS '공지사항 첨부 파일 - 공지사항 관련 첨부 파일';
COMMENT ON COLUMN notice_files.id IS '연결 ID (Primary Key)';
COMMENT ON COLUMN notice_files.notice_id IS '공지 ID (외래키) - notices 테이블 참조';
COMMENT ON COLUMN notice_files.file_id IS '파일 ID (외래키) - file_storage 테이블 참조';
COMMENT ON COLUMN notice_files.created_at IS '생성일시';

CREATE INDEX idx_notice_files_notice
  ON notice_files(notice_id, created_at);

-- ============================================
-- 3. 게시판 (3 Tables)
-- ============================================

-- BOARD_POSTS (게시글)
CREATE TABLE board_posts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_key     TEXT NOT NULL,
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  author_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  view_count    INT NOT NULL DEFAULT 0,
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  is_locked     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE board_posts IS '게시판 게시글 - 자유게시판, 질문게시판, 건의게시판';
COMMENT ON COLUMN board_posts.id IS '게시글 ID (Primary Key)';
COMMENT ON COLUMN board_posts.board_key IS '게시판 구분 키 - FREE: 자유게시판, QNA: 질문게시판, SUGGESTION: 건의게시판, NOTICE: 공지게시판';
COMMENT ON COLUMN board_posts.title IS '게시글 제목';
COMMENT ON COLUMN board_posts.content IS '게시글 내용 (HTML)';
COMMENT ON COLUMN board_posts.author_id IS '작성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN board_posts.view_count IS '조회수';
COMMENT ON COLUMN board_posts.is_pinned IS '상단 고정 여부';
COMMENT ON COLUMN board_posts.is_locked IS '잠금 여부 (댓글 작성 불가)';
COMMENT ON COLUMN board_posts.created_at IS '생성일시';
COMMENT ON COLUMN board_posts.updated_at IS '수정일시';

CREATE INDEX idx_board_posts_board_created
  ON board_posts(board_key, created_at DESC);

CREATE INDEX idx_board_posts_pinned
  ON board_posts(is_pinned DESC, created_at DESC);

CREATE INDEX idx_board_posts_author
  ON board_posts(author_id);

CREATE TRIGGER trg_board_posts_u
BEFORE UPDATE ON board_posts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- BOARD_FILES (게시판 첨부파일)
CREATE TABLE board_files (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     BIGINT NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
  file_id     BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE board_files IS '게시판 첨부 파일 - 게시글 첨부 파일';
COMMENT ON COLUMN board_files.id IS '연결 ID (Primary Key)';
COMMENT ON COLUMN board_files.post_id IS '게시글 ID (외래키) - board_posts 테이블 참조';
COMMENT ON COLUMN board_files.file_id IS '파일 ID (외래키) - file_storage 테이블 참조';
COMMENT ON COLUMN board_files.created_at IS '생성일시';

CREATE INDEX idx_board_files_post
  ON board_files(post_id, created_at);

-- BOARD_COMMENTS (댓글)
CREATE TABLE board_comments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id         BIGINT NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
  parent_id       BIGINT REFERENCES board_comments(id) ON DELETE CASCADE,
  author_id       BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  content         TEXT NOT NULL,
  is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
  guest_nickname  TEXT,
  guest_password  TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- author_id 없으면 guest_nickname/guest_password 필수
  CONSTRAINT chk_comment_author
    CHECK (
      author_id IS NOT NULL
      OR (guest_nickname IS NOT NULL AND guest_password IS NOT NULL)
    )
);

COMMENT ON TABLE board_comments IS '게시판 댓글 - 게시글에 대한 댓글 및 대댓글';
COMMENT ON COLUMN board_comments.id IS '댓글 ID (Primary Key)';
COMMENT ON COLUMN board_comments.post_id IS '게시글 ID (외래키) - board_posts 테이블 참조';
COMMENT ON COLUMN board_comments.parent_id IS '부모 댓글 ID (외래키) - 대댓글인 경우';
COMMENT ON COLUMN board_comments.author_id IS '작성자 ID (외래키) - employees 테이블 참조, 비회원이면 NULL';
COMMENT ON COLUMN board_comments.content IS '댓글 내용';
COMMENT ON COLUMN board_comments.is_deleted IS '삭제 여부';
COMMENT ON COLUMN board_comments.guest_nickname IS '비회원 닉네임 (비회원 댓글인 경우)';
COMMENT ON COLUMN board_comments.guest_password IS '비회원 비밀번호 해시 (비회원 댓글인 경우)';
COMMENT ON COLUMN board_comments.created_at IS '생성일시';
COMMENT ON COLUMN board_comments.updated_at IS '수정일시';

CREATE INDEX idx_board_comments_post
  ON board_comments(post_id, created_at)
  WHERE is_deleted = false;

CREATE INDEX idx_board_comments_parent
  ON board_comments(parent_id, created_at)
  WHERE parent_id IS NOT NULL AND is_deleted = false;

CREATE TRIGGER trg_board_comments_u
BEFORE UPDATE ON board_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 4. 갤러리 (2 Tables)
-- ============================================

-- GALLERY_ITEMS (갤러리)
CREATE TABLE gallery_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT,
  description   TEXT,
  category      TEXT DEFAULT 'GENERAL',
  event_date    DATE,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  is_public     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE gallery_items IS '갤러리 항목 - 사진첩, 행사 사진 등';
COMMENT ON COLUMN gallery_items.id IS '갤러리 항목 ID (Primary Key)';
COMMENT ON COLUMN gallery_items.title IS '제목';
COMMENT ON COLUMN gallery_items.description IS '설명';
COMMENT ON COLUMN gallery_items.category IS '카테고리 - GENERAL: 일반, EVENT: 행사, DAILY: 일상';
COMMENT ON COLUMN gallery_items.event_date IS '행사 일자';
COMMENT ON COLUMN gallery_items.created_by IS '작성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN gallery_items.is_public IS '공개 여부';
COMMENT ON COLUMN gallery_items.created_at IS '생성일시';
COMMENT ON COLUMN gallery_items.updated_at IS '수정일시';

CREATE INDEX idx_gallery_items_public_event
  ON gallery_items(is_public, event_date DESC)
  WHERE is_public = true;

CREATE INDEX idx_gallery_items_category
  ON gallery_items(category, is_public, event_date DESC)
  WHERE is_public = true;

CREATE TRIGGER trg_gallery_items_u
BEFORE UPDATE ON gallery_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- GALLERY_FILES (갤러리 파일)
CREATE TABLE gallery_files (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gallery_id    BIGINT NOT NULL REFERENCES gallery_items(id) ON DELETE CASCADE,
  file_id       BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE gallery_files IS '갤러리 파일 - 갤러리 항목에 포함된 이미지/동영상';
COMMENT ON COLUMN gallery_files.id IS '연결 ID (Primary Key)';
COMMENT ON COLUMN gallery_files.gallery_id IS '갤러리 ID (외래키) - gallery_items 테이블 참조';
COMMENT ON COLUMN gallery_files.file_id IS '파일 ID (외래키) - file_storage 테이블 참조';
COMMENT ON COLUMN gallery_files.sort_order IS '정렬 순서';
COMMENT ON COLUMN gallery_files.created_at IS '생성일시';

CREATE INDEX idx_gallery_files_gallery_sort
  ON gallery_files(gallery_id, sort_order, created_at);

-- ============================================
-- 5. 식단표 (2 Tables)
-- ============================================

-- MEAL_PLANS (식단표)
CREATE TABLE meal_plans (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_code  TEXT NOT NULL DEFAULT 'DEFAULT',
  week_start_date DATE NOT NULL,
  created_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  nutrition_manager TEXT,
  status         TEXT NOT NULL DEFAULT 'DRAFT',
  notes          TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT meal_plans_uniq_week UNIQUE (facility_code, week_start_date)
);

COMMENT ON TABLE meal_plans IS '주간 식단표 - 시설별 주간 식단 계획 헤더';
COMMENT ON COLUMN meal_plans.id IS '식단표 ID (Primary Key)';
COMMENT ON COLUMN meal_plans.facility_code IS '시설 코드 - 다중 시설 운영 시 구분';
COMMENT ON COLUMN meal_plans.week_start_date IS '주 시작일 (월요일)';
COMMENT ON COLUMN meal_plans.created_by IS '작성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN meal_plans.nutrition_manager IS '영양 관리자';
COMMENT ON COLUMN meal_plans.status IS '상태 - DRAFT: 작성중, PUBLISHED: 게시, ARCHIVED: 보관';
COMMENT ON COLUMN meal_plans.notes IS '비고';
COMMENT ON COLUMN meal_plans.created_at IS '생성일시';
COMMENT ON COLUMN meal_plans.updated_at IS '수정일시';

CREATE INDEX idx_meal_plans_status_week
  ON meal_plans(status, facility_code, week_start_date DESC)
  WHERE status = 'PUBLISHED';

CREATE TRIGGER trg_meal_plans_u
BEFORE UPDATE ON meal_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- MEAL_PLAN_ITEMS (식단 항목)
CREATE TABLE meal_plan_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_id  BIGINT NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
  meal_date     DATE NOT NULL,
  meal_type     TEXT NOT NULL,
  menu_content  TEXT NOT NULL,
  image_url     TEXT,
  calories      INT,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE meal_plan_items IS '식단표 세부 항목 - 요일/식사별 메뉴 구성';
COMMENT ON COLUMN meal_plan_items.id IS '항목 ID (Primary Key)';
COMMENT ON COLUMN meal_plan_items.meal_plan_id IS '식단표 ID (외래키) - meal_plans 테이블 참조';
COMMENT ON COLUMN meal_plan_items.meal_date IS '식사 날짜';
COMMENT ON COLUMN meal_plan_items.meal_type IS '식사 유형 - BREAKFAST: 아침, LUNCH: 점심, DINNER: 저녁, SNACK: 간식';
COMMENT ON COLUMN meal_plan_items.menu_content IS '메뉴 내용';
COMMENT ON COLUMN meal_plan_items.image_url IS '메뉴 이미지 URL';
COMMENT ON COLUMN meal_plan_items.calories IS '칼로리 (kcal)';
COMMENT ON COLUMN meal_plan_items.notes IS '비고';
COMMENT ON COLUMN meal_plan_items.created_at IS '생성일시';
COMMENT ON COLUMN meal_plan_items.updated_at IS '수정일시';

CREATE INDEX idx_meal_plan_items_plan_date
  ON meal_plan_items(meal_plan_id, meal_date, meal_type);

CREATE INDEX idx_meal_plan_items_date_range
  ON meal_plan_items(meal_date, meal_type);

CREATE TRIGGER trg_meal_plan_items_u
BEFORE UPDATE ON meal_plan_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 6. 프로그램 (3 Tables)
-- ============================================

-- PROGRAMS (프로그램)
CREATE TABLE programs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  category      TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  meta          JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE programs IS '프로그램 마스터 - 레크리에이션, 치료 프로그램 정의';
COMMENT ON COLUMN programs.id IS '프로그램 ID (Primary Key)';
COMMENT ON COLUMN programs.title IS '프로그램명';
COMMENT ON COLUMN programs.description IS '프로그램 설명';
COMMENT ON COLUMN programs.category IS '카테고리 - EXERCISE: 운동, MUSIC: 음악, COGNITIVE: 인지, ART: 미술, CRAFT: 공예, SPORTS: 스포츠, RECREATION: 레크리에이션, OTHER: 기타';
COMMENT ON COLUMN programs.is_active IS '활성화 여부';
COMMENT ON COLUMN programs.created_by IS '생성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN programs.meta IS '추가 메타데이터 (JSON)';
COMMENT ON COLUMN programs.created_at IS '생성일시';
COMMENT ON COLUMN programs.updated_at IS '수정일시';

CREATE INDEX idx_programs_active_category
  ON programs(is_active, category)
  WHERE is_active = true;

CREATE TRIGGER trg_programs_u
BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PROGRAM_SCHEDULES (프로그램 일정)
CREATE TABLE program_schedules (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id    BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  starts_at     TIMESTAMPTZ NOT NULL,
  ends_at       TIMESTAMPTZ NOT NULL,
  location      TEXT,
  capacity      INT,
  status        TEXT NOT NULL DEFAULT 'PLANNED',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT program_schedules_time_ck
    CHECK (ends_at > starts_at)
);

COMMENT ON TABLE program_schedules IS '프로그램 일정 - 프로그램 실행 인스턴스';
COMMENT ON COLUMN program_schedules.id IS '일정 ID (Primary Key)';
COMMENT ON COLUMN program_schedules.program_id IS '프로그램 ID (외래키) - programs 테이블 참조';
COMMENT ON COLUMN program_schedules.starts_at IS '시작일시';
COMMENT ON COLUMN program_schedules.ends_at IS '종료일시';
COMMENT ON COLUMN program_schedules.location IS '장소';
COMMENT ON COLUMN program_schedules.capacity IS '정원 (최대 참가 인원)';
COMMENT ON COLUMN program_schedules.status IS '상태 - PLANNED: 계획, CONFIRMED: 확정, ONGOING: 진행중, DONE: 완료, CANCELLED: 취소';
COMMENT ON COLUMN program_schedules.created_at IS '생성일시';
COMMENT ON COLUMN program_schedules.updated_at IS '수정일시';

CREATE INDEX idx_program_schedules_program_time
  ON program_schedules(program_id, starts_at);

CREATE INDEX idx_program_schedules_upcoming
  ON program_schedules(program_id, starts_at, status);

CREATE TRIGGER trg_program_schedules_u
BEFORE UPDATE ON program_schedules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PROGRAM_ATTENDANCE (프로그램 참석)
CREATE TABLE program_attendance (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id     BIGINT NOT NULL REFERENCES program_schedules(id) ON DELETE CASCADE,
  resident_id     BIGINT REFERENCES residents(id) ON DELETE CASCADE,
  employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  role            TEXT NOT NULL DEFAULT 'PARTICIPANT',
  attended        BOOLEAN NOT NULL DEFAULT FALSE,
  checked_at      TIMESTAMPTZ,
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT program_attendance_uniq
    UNIQUE (schedule_id, resident_id)
);

COMMENT ON TABLE program_attendance IS '프로그램 참석 기록 - 입소자 및 직원의 프로그램 참여 기록';
COMMENT ON COLUMN program_attendance.id IS '참석 ID (Primary Key)';
COMMENT ON COLUMN program_attendance.schedule_id IS '일정 ID (외래키) - program_schedules 테이블 참조';
COMMENT ON COLUMN program_attendance.resident_id IS '입소자 ID (외래키) - 참가자가 입소자인 경우';
COMMENT ON COLUMN program_attendance.employee_id IS '직원 ID (외래키) - 참가자 또는 진행자가 직원인 경우';
COMMENT ON COLUMN program_attendance.role IS '역할 - PARTICIPANT: 참가자, HELPER: 보조자, FACILITATOR: 진행자';
COMMENT ON COLUMN program_attendance.attended IS '참석 여부';
COMMENT ON COLUMN program_attendance.checked_at IS '체크인 일시';
COMMENT ON COLUMN program_attendance.notes IS '비고';
COMMENT ON COLUMN program_attendance.created_at IS '생성일시';

CREATE INDEX idx_program_attendance_schedule
  ON program_attendance(schedule_id, attended);

-- ============================================
-- 7. 면회 및 상담 (2 Tables)
-- ============================================

-- VISIT_RESERVATIONS (면회 예약)
CREATE TABLE visit_reservations (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_name          TEXT NOT NULL,
  visitor_phone         TEXT NOT NULL,
  visitor_relationship  TEXT NOT NULL,
  resident_name         TEXT NOT NULL,
  visit_date            DATE NOT NULL,
  visit_time            TEXT NOT NULL,
  visitor_count         INT NOT NULL DEFAULT 1,
  visit_purpose         TEXT,
  health_check_symptoms BOOLEAN NOT NULL DEFAULT FALSE,
  health_check_assistance BOOLEAN NOT NULL DEFAULT FALSE,
  notes                 TEXT,
  is_consented          BOOLEAN NOT NULL DEFAULT FALSE,
  status                TEXT NOT NULL DEFAULT 'PENDING',
  ip_address            TEXT,
  user_agent            TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE visit_reservations IS '면회 예약 - 홈페이지 면회 예약 신청 관리';
COMMENT ON COLUMN visit_reservations.id IS '예약 ID (Primary Key)';
COMMENT ON COLUMN visit_reservations.visitor_name IS '방문자 성함';
COMMENT ON COLUMN visit_reservations.visitor_phone IS '방문자 연락처';
COMMENT ON COLUMN visit_reservations.visitor_relationship IS '어르신과의 관계';
COMMENT ON COLUMN visit_reservations.resident_name IS '어르신 성함';
COMMENT ON COLUMN visit_reservations.visit_date IS '방문 희망일';
COMMENT ON COLUMN visit_reservations.visit_time IS '방문 희망시간';
COMMENT ON COLUMN visit_reservations.visitor_count IS '방문 인원';
COMMENT ON COLUMN visit_reservations.visit_purpose IS '방문 목적';
COMMENT ON COLUMN visit_reservations.health_check_symptoms IS '감염 증상 여부 (발열, 기침 등)';
COMMENT ON COLUMN visit_reservations.health_check_assistance IS '이동 보조 필요 여부';
COMMENT ON COLUMN visit_reservations.notes IS '추가 요청사항';
COMMENT ON COLUMN visit_reservations.is_consented IS '개인정보 수집 동의 여부';
COMMENT ON COLUMN visit_reservations.status IS '처리 상태 (PENDING, APPROVED, REJECTED, CANCELLED)';
COMMENT ON COLUMN visit_reservations.ip_address IS '신청 IP 주소';
COMMENT ON COLUMN visit_reservations.user_agent IS '사용자 브라우저 정보';
COMMENT ON COLUMN visit_reservations.created_at IS '신청 시각';
COMMENT ON COLUMN visit_reservations.updated_at IS '수정 시각';

CREATE TRIGGER trg_visit_reservations_u
BEFORE UPDATE ON visit_reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- WEB_INQUIRIES (웹사이트 상담 문의)
CREATE TABLE web_inquiries (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  phone         TEXT NOT NULL,
  email         TEXT,
  type          TEXT NOT NULL,
  resident_age  TEXT,
  care_grade    TEXT,
  preferred_date DATE,
  message       TEXT,
  is_consented  BOOLEAN NOT NULL DEFAULT FALSE,
  status        TEXT NOT NULL DEFAULT 'PENDING',
  ip_address    TEXT,
  user_agent    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE web_inquiries IS '웹사이트 상담 문의 - 홈페이지 상담 신청 접수용';
COMMENT ON COLUMN web_inquiries.id IS '문의 ID (Primary Key)';
COMMENT ON COLUMN web_inquiries.name IS '상담자 이름';
COMMENT ON COLUMN web_inquiries.phone IS '상담자 연락처';
COMMENT ON COLUMN web_inquiries.email IS '이메일';
COMMENT ON COLUMN web_inquiries.type IS '문의 유형 (입소 상담, 비용 상담 등)';
COMMENT ON COLUMN web_inquiries.resident_age IS '어르신 연령';
COMMENT ON COLUMN web_inquiries.care_grade IS '장기요양등급';
COMMENT ON COLUMN web_inquiries.preferred_date IS '방문 상담 희망일';
COMMENT ON COLUMN web_inquiries.message IS '상세 문의사항';
COMMENT ON COLUMN web_inquiries.is_consented IS '개인정보 수집 동의 여부';
COMMENT ON COLUMN web_inquiries.status IS '처리 상태 (PENDING, IN_PROGRESS, DONE, CANCELLED)';
COMMENT ON COLUMN web_inquiries.ip_address IS '문의 접수 IP 주소';
COMMENT ON COLUMN web_inquiries.user_agent IS '사용자 브라우저 정보';
COMMENT ON COLUMN web_inquiries.created_at IS '문의 생성 시각';
COMMENT ON COLUMN web_inquiries.updated_at IS '수정 시각';

CREATE TRIGGER trg_web_inquiries_u
BEFORE UPDATE ON web_inquiries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 8. 팝업 및 배너 (1 Table)
-- ============================================

-- POPUP_BANNERS (팝업 배너)
CREATE TABLE popup_banners (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           TEXT NOT NULL,
  content         TEXT,
  image_url       TEXT,
  link_url        TEXT,
  display_type    TEXT NOT NULL DEFAULT 'POPUP',
  position        TEXT,
  width           INT,
  height          INT,
  start_date      DATE NOT NULL,
  end_date        DATE NOT NULL,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  show_once       BOOLEAN NOT NULL DEFAULT FALSE,
  priority        INT NOT NULL DEFAULT 0,
  created_by      BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE popup_banners IS '팝업 배너 - 홈페이지 팝업 및 모달 배너 관리';
COMMENT ON COLUMN popup_banners.id IS '배너 ID (Primary Key)';
COMMENT ON COLUMN popup_banners.title IS '배너 제목';
COMMENT ON COLUMN popup_banners.content IS '배너 내용';
COMMENT ON COLUMN popup_banners.image_url IS '이미지 URL';
COMMENT ON COLUMN popup_banners.link_url IS '링크 URL';
COMMENT ON COLUMN popup_banners.display_type IS '표시 유형 - POPUP, MODAL, BANNER';
COMMENT ON COLUMN popup_banners.position IS '표시 위치';
COMMENT ON COLUMN popup_banners.width IS '너비 (px)';
COMMENT ON COLUMN popup_banners.height IS '높이 (px)';
COMMENT ON COLUMN popup_banners.start_date IS '게시 시작일';
COMMENT ON COLUMN popup_banners.end_date IS '게시 종료일';
COMMENT ON COLUMN popup_banners.is_active IS '활성화 여부';
COMMENT ON COLUMN popup_banners.show_once IS '하루 동안 보지 않기 옵션 여부';
COMMENT ON COLUMN popup_banners.priority IS '우선순위 (높을수록 먼저 표시)';
COMMENT ON COLUMN popup_banners.created_by IS '작성자 ID (외래키) - employees 테이블 참조';
COMMENT ON COLUMN popup_banners.created_at IS '생성일시';
COMMENT ON COLUMN popup_banners.updated_at IS '수정일시';

CREATE INDEX idx_popup_banners_active_dates
  ON popup_banners(is_active, start_date, end_date)
  WHERE is_active = true;

CREATE INDEX idx_popup_banners_priority
  ON popup_banners(priority DESC);

CREATE TRIGGER trg_popup_banners_u
BEFORE UPDATE ON popup_banners
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 완료 메시지
-- ============================================

DO $$
BEGIN
  RAISE NOTICE '========================================';
  RAISE NOTICE 'Web 알림마당 DDL 실행 완료';
  RAISE NOTICE '========================================';
  RAISE NOTICE '';
  RAISE NOTICE '생성된 테이블:';
  RAISE NOTICE '  기본: 4 테이블 (departments, employee_roles, employees, file_storage)';
  RAISE NOTICE '  입소자: 1 테이블 (residents)';
  RAISE NOTICE '  공지사항: 2 테이블 (notices, notice_files)';
  RAISE NOTICE '  게시판: 3 테이블 (board_posts, board_files, board_comments)';
  RAISE NOTICE '  갤러리: 2 테이블 (gallery_items, gallery_files)';
  RAISE NOTICE '  식단표: 2 테이블 (meal_plans, meal_plan_items)';
  RAISE NOTICE '  프로그램: 3 테이블 (programs, program_schedules, program_attendance)';
  RAISE NOTICE '  면회/문의: 2 테이블 (visit_reservations, web_inquiries)';
  RAISE NOTICE '  팝업/배너: 1 테이블 (popup_banners)';
  RAISE NOTICE '';
  RAISE NOTICE '총 20개 테이블';
  RAISE NOTICE '';
  RAISE NOTICE '다음 단계:';
  RAISE NOTICE '  1. 30-web-views.sql 실행 (View 생성)';
  RAISE NOTICE '  2. 40-web-seed.sql 실행 (샘플 데이터)';
  RAISE NOTICE '  3. 99-web-final-setup.sql 실행 (최종 설정)';
  RAISE NOTICE '========================================';
END$$;
