-- Description : 40-ddl.sql - 📌 Agape-Care Core ERP PostgreSQL Table DDL (46 Tables)
-- Author : Shiwoo Min
-- Date : 2026-01-23
-- Schema : Agape-Care Nursing Home ERP (Residents, Staff, Care, Schedules, Accounting, CMS)

-- Extensions -----------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Utility: updated_at trigger -------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- 1. 조직 / 직원 -------------------------------------------------------------

-- DEPARTMENTS
CREATE TABLE departments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_departments_u
BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- EMPLOYEE_ROLES
CREATE TABLE employee_roles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,      -- 'ADMIN','NURSE','CARE_GIVER','COOK'...
  name        TEXT NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '{}'::jsonb, -- bitmask/flags in JSON
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_employee_roles_u
BEFORE UPDATE ON employee_roles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- EMPLOYEES (로그인 계정 포함)
CREATE TABLE employees (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  role_id         BIGINT REFERENCES employee_roles(id) ON DELETE SET NULL,
  email           CITEXT UNIQUE,
  password_hash   TEXT,
  name            TEXT NOT NULL,
  phone_number    TEXT,
  hire_date       DATE,
  resign_date     DATE,
  status          TEXT NOT NULL DEFAULT 'ACTIVE',
  is_admin        BOOLEAN NOT NULL DEFAULT FALSE,
  meta            JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT employees_status_ck
    CHECK (status IN ('ACTIVE','ON_LEAVE','INACTIVE'))
);

CREATE TRIGGER trg_employees_u
BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. 입소자 / 건강정보 --------------------------------------------------------

-- RESIDENTS
CREATE TABLE residents (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              TEXT NOT NULL UNIQUE,  -- 내부 관리번호
  name              TEXT NOT NULL,
  birthday          DATE,
  gender            TEXT,                  -- 'M','F','OTHER'
  national_id_hash  TEXT,                  -- 식별자 해시
  admission_date    DATE,
  discharge_date    DATE,
  status            TEXT NOT NULL DEFAULT 'ADMITTED',
  guardian_name     TEXT,
  guardian_phone    TEXT,
  memo              TEXT,
  meta              JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT residents_status_ck
    CHECK (status IN ('ADMITTED','ON_LEAVE','DISCHARGED','PENDING'))
);

CREATE TRIGGER trg_residents_u
BEFORE UPDATE ON residents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RESIDENT_ROOMS (생활실/침대 배정 히스토리)
CREATE TABLE resident_rooms (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id   BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  room_label    TEXT NOT NULL,            -- '101-1', '201B' 등
  bed_label     TEXT,
  starts_at     DATE NOT NULL,
  ends_at       DATE,
  is_primary    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resident_rooms_date_ck
    CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX idx_resident_rooms_resident
  ON resident_rooms(resident_id, starts_at);

CREATE TRIGGER trg_resident_rooms_u
BEFORE UPDATE ON resident_rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RESIDENT_CONTACTS (추가 보호자/연락처)
CREATE TABLE resident_contacts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id   BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  relationship  TEXT,
  phone_number  TEXT,
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_resident_contacts_u
BEFORE UPDATE ON resident_contacts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RESIDENT_HEALTH_NOTES (간단 메모/상태 기록)
CREATE TABLE resident_health_notes (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id   BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  recorded_by   BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  note_type     TEXT NOT NULL DEFAULT 'GENERAL', -- 'GENERAL','NUTRITION','MOBILITY', ...
  content       TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RESIDENT_MEDICATIONS (투약 기록)
CREATE TABLE resident_medications (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id   BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  prescribed_by TEXT,
  drug_name     TEXT NOT NULL,
  dosage        TEXT NOT NULL,
  schedule      TEXT,                        -- '1-0-1' 등
  start_date    DATE NOT NULL,
  end_date      DATE,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_resident_medications_u
BEFORE UPDATE ON resident_medications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RESIDENT_VITALS (활력징후)
CREATE TABLE resident_vitals (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id   BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  recorded_by   BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  measured_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  systolic_bp   INT,      -- 수축기
  diastolic_bp  INT,      -- 이완기
  heart_rate    INT,
  temperature   NUMERIC(4,1),
  respiratory_rate INT,
  spo2          INT,
  notes         TEXT
);

CREATE INDEX idx_resident_vitals_resident_time
  ON resident_vitals(resident_id, measured_at DESC);

-- 3. 식단 / 프로그램 ----------------------------------------------------------

-- MEAL_PLANS (주간 식단표 헤더)
CREATE TABLE meal_plans (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_code  TEXT NOT NULL DEFAULT 'DEFAULT',
  week_start_date DATE NOT NULL,
  created_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  status         TEXT NOT NULL DEFAULT 'DRAFT',  -- 'DRAFT','PUBLISHED','ARCHIVED'
  notes          TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT meal_plans_uniq_week UNIQUE (facility_code, week_start_date)
);

CREATE TRIGGER trg_meal_plans_u
BEFORE UPDATE ON meal_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- MEAL_PLAN_ITEMS (요일/식사별 메뉴)
CREATE TABLE meal_plan_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_id  BIGINT NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
  meal_date     DATE NOT NULL,
  meal_type     TEXT NOT NULL,           -- 'BREAKFAST','LUNCH','DINNER','SNACK'
  main_menu     TEXT NOT NULL,
  side_menu     TEXT,
  soup          TEXT,
  dessert       TEXT,
  calories      INT,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT meal_plan_items_type_ck
    CHECK (meal_type IN ('BREAKFAST','LUNCH','DINNER','SNACK'))
);

CREATE INDEX idx_meal_plan_items_plan_date
  ON meal_plan_items(meal_plan_id, meal_date, meal_type);

CREATE TRIGGER trg_meal_plan_items_u
BEFORE UPDATE ON meal_plan_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PROGRAMS (프로그램 마스터)
CREATE TABLE programs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  category      TEXT,                -- 'EXERCISE','MUSIC','COGNITIVE', ...
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  meta          JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_programs_u
BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PROGRAM_SCHEDULES (일정 인스턴스)
CREATE TABLE program_schedules (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id    BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  starts_at     TIMESTAMPTZ NOT NULL,
  ends_at       TIMESTAMPTZ NOT NULL,
  location      TEXT,
  capacity      INT,
  status        TEXT NOT NULL DEFAULT 'PLANNED', -- 'PLANNED','CONFIRMED','CANCELLED','DONE'
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT program_schedules_time_ck
    CHECK (ends_at > starts_at),
  CONSTRAINT program_schedules_status_ck
    CHECK (status IN ('PLANNED','CONFIRMED','CANCELLED','DONE'))
);

CREATE INDEX idx_program_schedules_program_time
  ON program_schedules(program_id, starts_at);

CREATE TRIGGER trg_program_schedules_u
BEFORE UPDATE ON program_schedules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PROGRAM_ATTENDANCE (참여자 출석)
CREATE TABLE program_attendance (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id     BIGINT NOT NULL REFERENCES program_schedules(id) ON DELETE CASCADE,
  resident_id     BIGINT REFERENCES residents(id) ON DELETE CASCADE,
  employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  role            TEXT NOT NULL DEFAULT 'PARTICIPANT', -- 'PARTICIPANT','HELPER'
  attended        BOOLEAN NOT NULL DEFAULT FALSE,
  checked_at      TIMESTAMPTZ,
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT program_attendance_uniq
    UNIQUE (schedule_id, resident_id)
);

-- 4. 케어 플랜 / 상담 / 사건 -----------------------------------------------

-- CARE_PLANS
CREATE TABLE care_plans (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id    BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  created_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  title          TEXT NOT NULL,
  goal_summary   TEXT,
  start_date     DATE NOT NULL,
  end_date       DATE,
  status         TEXT NOT NULL DEFAULT 'ACTIVE', -- 'ACTIVE','COMPLETED','CANCELLED'
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_care_plans_u
BEFORE UPDATE ON care_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CARE_PLAN_ITEMS
CREATE TABLE care_plan_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  care_plan_id   BIGINT NOT NULL REFERENCES care_plans(id) ON DELETE CASCADE,
  sequence_no    INT NOT NULL,
  description    TEXT NOT NULL,
  frequency      TEXT,                -- 'DAILY','WEEKLY', 등
  notes          TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT care_plan_items_seq_uniq
    UNIQUE (care_plan_id, sequence_no)
);

CREATE TRIGGER trg_care_plan_items_u
BEFORE UPDATE ON care_plan_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- CONSULTATION_RECORDS (상담/면담 기록)
CREATE TABLE consultation_records (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id    BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  counselor_id   BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  consulted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  type           TEXT NOT NULL DEFAULT 'GENERAL', -- 'FAMILY','NURSE','SOCIAL_WORKER'
  channel        TEXT,                             -- 'IN_PERSON','PHONE','VIDEO'
  summary        TEXT NOT NULL,
  details        TEXT,
  follow_up_date DATE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- CONSULTATION_FILES
CREATE TABLE consultation_files (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_id      BIGINT NOT NULL REFERENCES consultation_records(id) ON DELETE CASCADE,
  file_id              BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- INCIDENTS (사건/사고 보고)
CREATE TABLE incidents (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id    BIGINT REFERENCES residents(id) ON DELETE SET NULL,
  reported_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  occurred_at    TIMESTAMPTZ NOT NULL,
  severity       TEXT NOT NULL,       -- 'LOW','MEDIUM','HIGH','CRITICAL'
  title          TEXT NOT NULL,
  description    TEXT NOT NULL,
  location       TEXT,
  status         TEXT NOT NULL DEFAULT 'OPEN', -- 'OPEN','IN_REVIEW','CLOSED'
  action_taken   TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT incidents_severity_ck
    CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  CONSTRAINT incidents_status_ck
    CHECK (status IN ('OPEN','IN_REVIEW','CLOSED'))
);

CREATE TRIGGER trg_incidents_u
BEFORE UPDATE ON incidents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- INCIDENT_FILES
CREATE TABLE incident_files (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id   BIGINT NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  file_id       BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- CARE_TASKS (요양보호사 투입 업무)
CREATE TABLE care_tasks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id    BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
  assigned_to    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  due_at         TIMESTAMPTZ,
  title          TEXT NOT NULL,
  description    TEXT,
  status         TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING','IN_PROGRESS','DONE','CANCELLED'
  priority       TEXT NOT NULL DEFAULT 'NORMAL',  -- 'LOW','NORMAL','HIGH'
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_care_tasks_u
BEFORE UPDATE ON care_tasks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. 공지 / 게시판 / 갤러리 ---------------------------------------------------

-- NOTICES
CREATE TABLE notices (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  category      TEXT DEFAULT 'GENERAL',
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  published_at  TIMESTAMPTZ,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_notices_u
BEFORE UPDATE ON notices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- NOTICE_FILES
CREATE TABLE notice_files (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id   BIGINT NOT NULL REFERENCES notices(id) ON DELETE CASCADE,
  file_id     BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- BOARD_POSTS
CREATE TABLE board_posts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_key     TEXT NOT NULL,               -- 'FREE','QNA','SUGGESTION'
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  author_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  view_count    INT NOT NULL DEFAULT 0,
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  is_locked     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_board_posts_board_created
  ON board_posts(board_key, created_at DESC);

CREATE TRIGGER trg_board_posts_u
BEFORE UPDATE ON board_posts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- BOARD_FILES
CREATE TABLE board_files (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     BIGINT NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
  file_id     BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- BOARD_COMMENTS
CREATE TABLE board_comments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       BIGINT NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
  parent_id     BIGINT REFERENCES board_comments(id) ON DELETE CASCADE,
  author_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  content       TEXT NOT NULL,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_board_comments_u
BEFORE UPDATE ON board_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- GALLERY_ITEMS
CREATE TABLE gallery_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT,
  description   TEXT,
  event_date    DATE,
  created_by    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  is_public     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_gallery_items_u
BEFORE UPDATE ON gallery_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- GALLERY_FILES
CREATE TABLE gallery_files (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gallery_id    BIGINT NOT NULL REFERENCES gallery_items(id) ON DELETE CASCADE,
  file_id       BIGINT NOT NULL REFERENCES file_storage(id) ON DELETE CASCADE,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. 출결 / 근무표 ------------------------------------------------------------

-- ATTENDANCE_RECORDS
CREATE TABLE attendance_records (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  work_date     DATE NOT NULL,
  check_in_at   TIMESTAMPTZ,
  check_out_at  TIMESTAMPTZ,
  status        TEXT NOT NULL DEFAULT 'PRESENT', -- 'PRESENT','ABSENT','LATE','ON_LEAVE'
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT attendance_records_uniq
    UNIQUE (employee_id, work_date)
);

CREATE TRIGGER trg_attendance_records_u
BEFORE UPDATE ON attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SHIFT_TEMPLATES (근무 패턴)
CREATE TABLE shift_templates (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT NOT NULL UNIQUE,      -- 'DAY','EVE','NIGHT'
  name          TEXT NOT NULL,
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT shift_templates_time_ck
    CHECK (start_time <> end_time)
);

CREATE TRIGGER trg_shift_templates_u
BEFORE UPDATE ON shift_templates
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SHIFT_ASSIGNMENTS (직원 근무 배정)
CREATE TABLE shift_assignments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id     BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  work_date       DATE NOT NULL,
  shift_template_id BIGINT REFERENCES shift_templates(id) ON DELETE SET NULL,
  starts_at       TIMESTAMPTZ NOT NULL,
  ends_at         TIMESTAMPTZ NOT NULL,
  period          TSTZRANGE GENERATED ALWAYS AS
                    (tstzrange(starts_at, ends_at, '[)')) STORED,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT shift_assignments_time_ck
    CHECK (ends_at > starts_at),
  CONSTRAINT shift_assignments_uniq
    UNIQUE (employee_id, work_date)
);

CREATE TRIGGER trg_shift_assignments_u
BEFORE UPDATE ON shift_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 같은 직원의 겹치는 근무 방지
ALTER TABLE shift_assignments
  ADD CONSTRAINT shift_assignments_no_overlap
  EXCLUDE USING gist (
    employee_id WITH =,
    period      WITH &&
  );

-- LEAVE_REQUESTS
CREATE TABLE leave_requests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  start_date    DATE NOT NULL,
  end_date      DATE NOT NULL,
  type          TEXT NOT NULL,    -- 'ANNUAL','SICK','OTHER'
  reason        TEXT,
  status        TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING','APPROVED','REJECTED','CANCELLED'
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_date_ck
    CHECK (end_date >= start_date)
);

CREATE TRIGGER trg_leave_requests_u
BEFORE UPDATE ON leave_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- LEAVE_APPROVALS
CREATE TABLE leave_approvals (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_request_id BIGINT NOT NULL REFERENCES leave_requests(id) ON DELETE CASCADE,
  approved_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  approved_at     TIMESTAMPTZ,
  decision        TEXT NOT NULL, -- 'APPROVED','REJECTED'
  comment         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. 회계 / 급여 / 매입 -------------------------------------------------------

-- ACCOUNT_CATEGORIES
CREATE TABLE account_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL,        -- 'INCOME','EXPENSE','ASSET','LIABILITY'
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_account_categories_u
BEFORE UPDATE ON account_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ACCOUNTS
CREATE TABLE accounts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id     BIGINT REFERENCES account_categories(id) ON DELETE SET NULL,
  code            TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  description     TEXT,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_accounts_u
BEFORE UPDATE ON accounts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SUPPLIERS
CREATE TABLE suppliers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  business_no   TEXT,
  phone_number  TEXT,
  email         CITEXT,
  address       TEXT,
  memo          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_suppliers_u
BEFORE UPDATE ON suppliers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- TRANSACTIONS (회계 전표 헤더)
CREATE TABLE transactions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_date       DATE NOT NULL,
  description    TEXT,
  reference_no   TEXT,
  supplier_id    BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  created_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  total_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
  currency       TEXT NOT NULL DEFAULT 'KRW',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_transactions_date
  ON transactions(txn_date DESC);

CREATE TRIGGER trg_transactions_u
BEFORE UPDATE ON transactions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- TRANSACTION_ITEMS (분개 라인)
CREATE TABLE transaction_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  account_id     BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
  line_no        INT NOT NULL,
  description    TEXT,
  debit_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
  credit_amount  NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT transaction_items_line_uniq
    UNIQUE (transaction_id, line_no)
);

-- PAYROLL_RECORDS
CREATE TABLE payroll_records (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id    BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  period_start   DATE NOT NULL,
  period_end     DATE NOT NULL,
  base_salary    NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_allowance NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_deduction NUMERIC(14,2) NOT NULL DEFAULT 0,
  net_pay        NUMERIC(14,2) NOT NULL DEFAULT 0,
  paid_at        TIMESTAMPTZ,
  status         TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING','PAID','CANCELLED'
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_payroll_records_u
BEFORE UPDATE ON payroll_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- PAYROLL_ITEMS
CREATE TABLE payroll_items (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_id      BIGINT NOT NULL REFERENCES payroll_records(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL,          -- 'ALLOWANCE','DEDUCTION'
  name            TEXT NOT NULL,
  amount          NUMERIC(14,2) NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- INVOICE_HEADERS (청구/매출)
CREATE TABLE invoice_headers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no      TEXT NOT NULL UNIQUE,
  resident_id     BIGINT REFERENCES residents(id) ON DELETE SET NULL,
  issue_date      DATE NOT NULL,
  due_date        DATE,
  total_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
  status          TEXT NOT NULL DEFAULT 'DRAFT', -- 'DRAFT','ISSUED','PAID','CANCELLED'
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_invoice_headers_u
BEFORE UPDATE ON invoice_headers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- INVOICE_ITEMS
CREATE TABLE invoice_items (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id      BIGINT NOT NULL REFERENCES invoice_headers(id) ON DELETE CASCADE,
  line_no         INT NOT NULL,
  description     TEXT NOT NULL,
  quantity        NUMERIC(10,2) NOT NULL DEFAULT 1,
  unit_price      NUMERIC(14,2) NOT NULL DEFAULT 0,
  amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_line_uniq
    UNIQUE (invoice_id, line_no)
);

-- 8. 공통 파일 / 로그 / 설정 / 알림 큐 --------------------------------------

-- FILE_STORAGE (공통 파일 메타)
CREATE TABLE file_storage (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket          TEXT NOT NULL DEFAULT 'default',
  path            TEXT NOT NULL,
  original_name   TEXT,
  mime_type       TEXT,
  size_bytes      BIGINT,
  checksum        TEXT,
  created_by      BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_file_storage_bucket_path
  ON file_storage(bucket, path);

-- AUDIT_LOGS
CREATE TABLE audit_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id      BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  action        TEXT NOT NULL,
  entity_type   TEXT,
  entity_id     BIGINT,
  changes       JSONB,
  ip_address    TEXT,
  user_agent    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_entity
  ON audit_logs(entity_type, entity_id);

-- SYSTEM_SETTINGS (Key-Value 설정)
CREATE TABLE system_settings (
  key           TEXT PRIMARY KEY,
  value         JSONB NOT NULL,
  description   TEXT,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- NOTIFICATION_QUEUE (비동기 발송 큐)
CREATE TABLE notification_queue (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel       TEXT NOT NULL,       -- 'PUSH','SMS','EMAIL','INAPP'
  target_type   TEXT NOT NULL,       -- 'RESIDENT','EMPLOYEE','GUARDIAN'
  target_id     BIGINT,
  title         TEXT,
  body          TEXT,
  payload       JSONB NOT NULL DEFAULT '{}'::jsonb,
  scheduled_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at       TIMESTAMPTZ,
  status        TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING','SENT','FAILED','CANCELLED'
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notification_queue_status_sched
  ON notification_queue(status, scheduled_at);

-- 완료 메시지 ---------------------------------------------------------------

DO $$
BEGIN
  RAISE NOTICE 'Agape-Care core schema created successfully (46 tables)';
END$$;
